module.exports = {
  '1CR': {
    id: 1,
    name: '1CRedit',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ABY: {
    id: 2,
    name: 'ArtByte',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AC: {
    id: 3,
    name: 'AsiaCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ACH: {
    id: 4,
    name: 'Altcoin Herald',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ADN: {
    id: 5,
    name: 'Aiden',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AEON: {
    id: 6,
    name: 'AEON Coin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress:
      'WmrzAb4yy6i4otzaTZznsmaeBn8UKoBqS14XdW2DDzXr3DQnwz4o1XPJAJuo7QTqSoD9WVrdEQfn15udzhsJWmNR1jAEETQ2N',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AERO: {
    id: 7,
    name: 'Aerocoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AIR: {
    id: 8,
    name: 'AIRcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AMP: {
    id: 275,
    name: 'Synereo AMP',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '5.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  APH: {
    id: 9,
    name: 'AphroditeCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ARCH: {
    id: 258,
    name: 'ARCHcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ARDR: {
    id: 285,
    name: 'Ardor',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '2.00000000',
    minConf: 20,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  ATOM: {
    id: 313,
    name: 'Cosmos',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00500000',
    minConf: 0,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  AUR: {
    id: 10,
    name: 'Auroracoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  AXIS: {
    id: 11,
    name: 'Axis',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BALLS: {
    id: 12,
    name: 'Snowballs',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '6.40000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BANK: {
    id: 13,
    name: 'BankCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BAT: {
    id: 302,
    name: 'Basic Attention Token',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '9.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BBL: {
    id: 14,
    name: 'BitBlock',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BBR: {
    id: 15,
    name: 'Boolberry',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.00500000',
    minConf: 10000,
    depositAddress:
      '1D9hJ1nEjwuhxZMk6fupoTjKLtS2KzkfCQ7kF25k5B6Sc4UJjt9FrvDNYomVd4ZVHv36FskVRJGZa1JZAnZ35GiuAHf7gBy',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BCC: {
    id: 16,
    name: 'BTCtalkcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BCH: {
    id: 292,
    name: 'Bitcoin Cash (FROZEN)',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00010000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 1,
    isGeofenced: 0,
  },
  BCHABC: {
    id: 308,
    name: 'Bitcoin Cash',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 11,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BCHSV: {
    id: 309,
    name: 'Bitcoin SV',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 36,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BCN: {
    id: 17,
    name: 'Bytecoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 1000,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  BCY: {
    id: 269,
    name: 'BitCrystals',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '4.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BDC: {
    id: 18,
    name: 'Black Dragon Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BDG: {
    id: 19,
    name: 'Badgercoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BELA: {
    id: 20,
    name: 'Bela Legacy',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BITCNY: {
    id: 273,
    name: 'BitCNY',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress: 'poloniexwallet',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BITS: {
    id: 21,
    name: 'Bitstar',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BITUSD: {
    id: 272,
    name: 'BitUSD',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.15000000',
    minConf: 10000,
    depositAddress: 'poloniexwallet',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BLK: {
    id: 22,
    name: 'BlackCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BLOCK: {
    id: 23,
    name: 'Blocknet',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 100000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 1,
    isGeofenced: 0,
  },
  BLU: {
    id: 24,
    name: 'BlueCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BNS: {
    id: 25,
    name: 'BonusCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BNT: {
    id: 305,
    name: 'Bancor',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.10000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BONES: {
    id: 26,
    name: 'Bones',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BOST: {
    id: 27,
    name: 'BoostCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BTC: {
    id: 28,
    name: 'Bitcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00050000',
    minConf: 1,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BTCD: {
    id: 29,
    name: 'BitcoinDark',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BTCS: {
    id: 30,
    name: 'Bitcoin-sCrypt',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BTM: {
    id: 31,
    name: 'Bitmark',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BTS: {
    id: 32,
    name: 'BitShares',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '5.00000000',
    minConf: 50,
    depositAddress: 'poloniexwallet',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  BURN: {
    id: 33,
    name: 'BurnerCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  BURST: {
    id: 34,
    name: 'Burst',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  C2: {
    id: 35,
    name: 'Coin2.0',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CACH: {
    id: 36,
    name: 'CACHeCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CAI: {
    id: 37,
    name: 'CaiShen',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CC: {
    id: 38,
    name: 'Colbert Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CCN: {
    id: 39,
    name: 'Cannacoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CGA: {
    id: 40,
    name: 'Cryptographic Anomaly',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CHA: {
    id: 41,
    name: 'Chancecoin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CINNI: {
    id: 42,
    name: 'CinniCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CLAM: {
    id: 43,
    name: 'CLAMS',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 6,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  CNL: {
    id: 44,
    name: 'ConcealCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CNMT: {
    id: 45,
    name: 'Coinomat1',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CNOTE: {
    id: 46,
    name: 'C-Note',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  COMM: {
    id: 47,
    name: 'CommunityCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CON: {
    id: 48,
    name: 'Coino',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CORG: {
    id: 49,
    name: 'CorgiCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CRYPT: {
    id: 50,
    name: 'CryptCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CURE: {
    id: 51,
    name: 'Curecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  CVC: {
    id: 294,
    name: 'Civic',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  CYC: {
    id: 52,
    name: 'Conspiracy Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DAO: {
    id: 279,
    name: 'The DAO',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DASH: {
    id: 60,
    name: 'Dash',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 50,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  DCR: {
    id: 277,
    name: 'Decred',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 4,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  DGB: {
    id: 53,
    name: 'DigiByte',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 40,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  DICE: {
    id: 54,
    name: 'NeoDICE',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DIEM: {
    id: 55,
    name: 'Diem',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DIME: {
    id: 56,
    name: 'Dimecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DIS: {
    id: 57,
    name: 'DistroCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DNS: {
    id: 58,
    name: 'BitShares DNS',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.50000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DOGE: {
    id: 59,
    name: 'Dogecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '100.00000000',
    minConf: 6,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  DRKC: {
    id: 61,
    name: 'DarkCash',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DRM: {
    id: 62,
    name: 'Dreamcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DSH: {
    id: 63,
    name: 'Dashcoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress:
      'D8PDwmpq4KMhTy6u8RvWt5PLTMwEayGN3jeYoS3pkJQJMULNt2CyYKXG7KhqSahe9DPppRKqzkWGoMjf8C4L2mzFAgsJZXs',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  DVK: {
    id: 64,
    name: 'DvoraKoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EAC: {
    id: 65,
    name: 'EarthCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EBT: {
    id: 66,
    name: 'EBTcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ECC: {
    id: 67,
    name: 'ECCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EFL: {
    id: 68,
    name: 'Electronic Gulden',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EMC2: {
    id: 69,
    name: 'Einsteinium',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EMO: {
    id: 70,
    name: 'EmotiCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ENC: {
    id: 71,
    name: 'Entropycoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EOS: {
    id: 298,
    name: 'EOS',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.00000000',
    minConf: 600,
    depositAddress: 'poloniexeos1',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  ETC: {
    id: 283,
    name: 'Ethereum Classic',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 600,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  ETH: {
    id: 267,
    name: 'Ethereum',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  eTOK: {
    id: 72,
    name: 'eToken',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EXE: {
    id: 73,
    name: 'Execoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  EXP: {
    id: 270,
    name: 'Expanse',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 8000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FAC: {
    id: 74,
    name: 'Faircoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FCN: {
    id: 75,
    name: 'Fantomcoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress:
      '6mkbrPdSAjeaQKCCx8Nus1JiKb4HdeTDXC4bEWunDzTMXMPESd7aFNYPAG1U4MUpnhHfJfzVyTqnRFRW2REKN6efBVRMoSY',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FCT: {
    id: 271,
    name: 'Factom',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 3,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  FIBRE: {
    id: 76,
    name: 'Fibrecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FLAP: {
    id: 77,
    name: 'FlappyCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FLDC: {
    id: 78,
    name: 'FoldingCoin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '750.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FLO: {
    id: 254,
    name: 'Florincoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FLT: {
    id: 79,
    name: 'FlutterCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FOAM: {
    id: 307,
    name: 'Foam',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  FOX: {
    id: 80,
    name: 'FoxCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FRAC: {
    id: 81,
    name: 'Fractalcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FRK: {
    id: 82,
    name: 'Franko',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FRQ: {
    id: 83,
    name: 'FairQuark',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FVZ: {
    id: 84,
    name: 'FVZCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FZ: {
    id: 85,
    name: 'Frozen',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  FZN: {
    id: 86,
    name: 'Fuzon',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GAME: {
    id: 93,
    name: 'GameCredits',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 80,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  GAP: {
    id: 87,
    name: 'Gapcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GAS: {
    id: 296,
    name: 'Gas',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 18,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  GDN: {
    id: 88,
    name: 'Global Denomination',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GEMZ: {
    id: 89,
    name: 'GetGems',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '500.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GEO: {
    id: 90,
    name: 'GeoCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GIAR: {
    id: 91,
    name: 'Giarcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GLB: {
    id: 92,
    name: 'Globe',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GML: {
    id: 94,
    name: 'GameleagueCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 1,
    isGeofenced: 0,
  },
  GNO: {
    id: 291,
    name: 'Gnosis',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01500000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GNS: {
    id: 95,
    name: 'GenesisCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GNT: {
    id: 290,
    name: 'Golem',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  GOLD: {
    id: 96,
    name: 'GoldEagles',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GPC: {
    id: 97,
    name: 'GROUPCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GPUC: {
    id: 98,
    name: 'GPU Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GRC: {
    id: 261,
    name: 'Gridcoin Research',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GRCX: {
    id: 99,
    name: 'Gridcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GRIN: {
    id: 314,
    name: 'Grin',
    humanType: 'MimbleWimble',
    currencyType: 'mimblewimble',
    txFee: '0.10000000',
    minConf: 15,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  GRS: {
    id: 100,
    name: 'Groestlcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 100000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  GUE: {
    id: 101,
    name: 'Guerillacoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  H2O: {
    id: 102,
    name: 'H2O Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HIRO: {
    id: 103,
    name: 'Hirocoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HOT: {
    id: 104,
    name: 'Hotcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HUC: {
    id: 105,
    name: 'Huntercoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HUGE: {
    id: 260,
    name: 'BIGcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 1,
    isGeofenced: 0,
  },
  HVC: {
    id: 106,
    name: 'Heavycoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HYP: {
    id: 107,
    name: 'HyperStake',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  HZ: {
    id: 108,
    name: 'Horizon',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  IFC: {
    id: 109,
    name: 'Infinitecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '2000.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  INDEX: {
    id: 265,
    name: 'CoinoIndex',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  IOC: {
    id: 263,
    name: 'IO Digital Currency',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ITC: {
    id: 110,
    name: 'Information Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  IXC: {
    id: 111,
    name: 'iXcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  JLH: {
    id: 112,
    name: 'jl777hodl',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  JPC: {
    id: 113,
    name: 'JackpotCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  JUG: {
    id: 114,
    name: 'JuggaloCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  KDC: {
    id: 115,
    name: 'KlondikeCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  KEY: {
    id: 116,
    name: 'KeyCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  KNC: {
    id: 301,
    name: 'Kyber',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.50000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  LBC: {
    id: 280,
    name: 'LBRY Credits',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.05000000',
    minConf: 11,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  LC: {
    id: 117,
    name: 'Limecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LCL: {
    id: 118,
    name: 'Limecoin Lite',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LEAF: {
    id: 119,
    name: 'Leafcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LGC: {
    id: 120,
    name: 'Logicoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LOL: {
    id: 121,
    name: 'LeagueCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LOOM: {
    id: 303,
    name: 'LOOM Network',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '19.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  LOVE: {
    id: 122,
    name: 'LOVEcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LPT: {
    id: 312,
    name: 'Livepeer',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.05000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  LQD: {
    id: 123,
    name: 'LIQUID',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LSK: {
    id: 278,
    name: 'Lisk',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 303,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  LTBC: {
    id: 124,
    name: 'LTBCoin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '15000.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  LTC: {
    id: 125,
    name: 'Litecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 4,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  LTCX: {
    id: 126,
    name: 'LiteCoinX',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MAID: {
    id: 127,
    name: 'MaidSafeCoin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '80.00000000',
    minConf: 1,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  MANA: {
    id: 306,
    name: 'Decentraland',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '22.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  MAST: {
    id: 128,
    name: 'MastiffCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MAX: {
    id: 129,
    name: 'MaxCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MCN: {
    id: 130,
    name: 'Moneta Verde',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress:
      'VdttvavdPJNGD4NzPQf8Hn4tWUGyy9mQ58ScwXxKbx9ve4Kp8xXZ1kD1KmXUMp5qtX8GmRgMk16aNVBhENEHNQAb3488Ha7Vv',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MEC: {
    id: 131,
    name: 'Megacoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  METH: {
    id: 132,
    name: 'CryptoMETH',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MIL: {
    id: 133,
    name: 'Millennium Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MIN: {
    id: 134,
    name: 'Minerals',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MINT: {
    id: 135,
    name: 'Mintcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MMC: {
    id: 136,
    name: 'MemoryCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MMNXT: {
    id: 137,
    name: 'MMNXT',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MMXIV: {
    id: 138,
    name: 'Maieuticoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MNTA: {
    id: 139,
    name: 'Moneta',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MON: {
    id: 140,
    name: 'Monocle',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MRC: {
    id: 141,
    name: 'microCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MRS: {
    id: 142,
    name: 'Marscoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MTS: {
    id: 144,
    name: 'Metiscoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MUN: {
    id: 145,
    name: 'Muniti',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MYR: {
    id: 146,
    name: 'Myriadcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  MZC: {
    id: 147,
    name: 'MazaCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  N5X: {
    id: 148,
    name: 'N5coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NAS: {
    id: 149,
    name: 'NAS',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NAUT: {
    id: 150,
    name: 'Nautiluscoin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address-payment-id',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NAV: {
    id: 151,
    name: 'NAVCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 480,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  NBT: {
    id: 152,
    name: 'NuBits',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NEOS: {
    id: 153,
    name: 'Neoscoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00010000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NL: {
    id: 154,
    name: 'Nanolite',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NMC: {
    id: 155,
    name: 'Namecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NMR: {
    id: 310,
    name: 'Numeraire',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.05000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  NOBL: {
    id: 156,
    name: 'NobleCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NOTE: {
    id: 157,
    name: 'DNotes',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NOXT: {
    id: 158,
    name: 'NobleNXT',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NRS: {
    id: 159,
    name: 'NoirShares',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NSR: {
    id: 160,
    name: 'NuShares',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '2.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NTX: {
    id: 161,
    name: 'NTX',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NXC: {
    id: 288,
    name: 'Nexium',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '10.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  NXT: {
    id: 162,
    name: 'NXT',
    humanType: 'Sweep to Main Account',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 24,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  NXTI: {
    id: 163,
    name: 'NXTInspect',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  OMG: {
    id: 295,
    name: 'OmiseGO',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.30000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  OMNI: {
    id: 143,
    name: 'Omni',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '4.00000000',
    minConf: 1,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  OPAL: {
    id: 164,
    name: 'Opal',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PAND: {
    id: 165,
    name: 'PandaCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PASC: {
    id: 289,
    name: 'PascalCoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 300,
    depositAddress: '86646-64',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  PAWN: {
    id: 166,
    name: 'Pawncoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PIGGY: {
    id: 167,
    name: 'New Piggycoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PINK: {
    id: 168,
    name: 'Pinkcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PLX: {
    id: 169,
    name: 'ParallaxCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PMC: {
    id: 170,
    name: 'Premine',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  POLY: {
    id: 311,
    name: 'Polymath',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.25000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  POT: {
    id: 171,
    name: 'PotCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PPC: {
    id: 172,
    name: 'Peercoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PRC: {
    id: 173,
    name: 'ProsperCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PRT: {
    id: 174,
    name: 'Particle',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  PTS: {
    id: 175,
    name: 'BitShares PTS',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '25.00000000',
    minConf: 10000,
    depositAddress: 'poloniexwallet',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  Q2C: {
    id: 176,
    name: 'QubitCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  QBK: {
    id: 177,
    name: 'Qibuck',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  QCN: {
    id: 178,
    name: 'QuazarCoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress:
      '1VQpANF1pcKHPRAsZpeyG4jLDd1kbPn32YMeXkr9n8jNFvf8aaJdecB3FyAvo7X1DWJDQt3nii9eUTP5kJSfRpL5AwT72FM',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  QORA: {
    id: 179,
    name: 'Qora',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  QTL: {
    id: 180,
    name: 'Quatloo',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  QTUM: {
    id: 304,
    name: 'Qtum',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 6,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  RADS: {
    id: 274,
    name: 'Radium',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  RBY: {
    id: 181,
    name: 'Rubycoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  RDD: {
    id: 182,
    name: 'Reddcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  REP: {
    id: 284,
    name: 'Augur',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 30,
    depositAddress: '',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 1,
  },
  RIC: {
    id: 183,
    name: 'Riecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  RZR: {
    id: 184,
    name: 'Razor',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SBD: {
    id: 282,
    name: 'Steem Dollars',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: 'poloniex',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SC: {
    id: 268,
    name: 'Siacoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '10.00000000',
    minConf: 6,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  SDC: {
    id: 185,
    name: 'Shadow',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SHIBE: {
    id: 186,
    name: 'ShibeCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SHOPX: {
    id: 187,
    name: 'ShopX',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SILK: {
    id: 188,
    name: 'Silkcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SJCX: {
    id: 189,
    name: 'Storjcoin X',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '3.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SLR: {
    id: 190,
    name: 'SolarCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SMC: {
    id: 191,
    name: 'SmartCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SNT: {
    id: 300,
    name: 'Status',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '200.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  SOC: {
    id: 192,
    name: 'SocialCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SPA: {
    id: 193,
    name: 'Spaincoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SQL: {
    id: 194,
    name: 'Squallcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SRCC: {
    id: 195,
    name: 'SourceCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SRG: {
    id: 196,
    name: 'Surge',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SSD: {
    id: 197,
    name: 'Sonic',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  STEEM: {
    id: 281,
    name: 'STEEM',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.01000000',
    minConf: 50,
    depositAddress: 'poloniex',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  STORJ: {
    id: 297,
    name: 'Storj',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  STR: {
    id: 198,
    name: 'Stellar',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.00001000',
    minConf: 2,
    depositAddress: 'GCF7F72LNF3ODSJIIWPJWEVWX33VT2SVZSUQ5NMDKDLK3N2NFCUAUHPT',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  STRAT: {
    id: 287,
    name: 'Stratis',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 24,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  SUM: {
    id: 199,
    name: 'SummerCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SUN: {
    id: 200,
    name: 'Suncoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SWARM: {
    id: 201,
    name: 'SWARM',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '1000.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SXC: {
    id: 202,
    name: 'Sexcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SYNC: {
    id: 203,
    name: 'Sync',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00010000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  SYS: {
    id: 204,
    name: 'Syscoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  TAC: {
    id: 205,
    name: 'Talkcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  TOR: {
    id: 206,
    name: 'TorCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  TRUST: {
    id: 207,
    name: 'TrustPlus',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  TWE: {
    id: 208,
    name: 'Twecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  UIS: {
    id: 209,
    name: 'Unitus',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ULTC: {
    id: 210,
    name: 'Umbrella-LTC',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  UNITY: {
    id: 211,
    name: 'SuperNET',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  URO: {
    id: 212,
    name: 'Uro',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  USDC: {
    id: 299,
    name: 'USD Coin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.02000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  USDE: {
    id: 213,
    name: 'USDE',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  USDT: {
    id: 214,
    name: 'Tether USD',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '10.00000000',
    minConf: 2,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  UTC: {
    id: 215,
    name: 'UltraCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  UTIL: {
    id: 216,
    name: 'UtilityCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  UVC: {
    id: 217,
    name: 'UniversityCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  VIA: {
    id: 218,
    name: 'Viacoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 60,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  VOOT: {
    id: 219,
    name: 'VootCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  VOX: {
    id: 276,
    name: 'Voxels',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  VRC: {
    id: 220,
    name: 'VeriCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  VTC: {
    id: 221,
    name: 'Vertcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 600,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  WC: {
    id: 222,
    name: 'WhiteCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  WDC: {
    id: 223,
    name: 'Worldcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  WIKI: {
    id: 224,
    name: 'Wikicoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.10000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  WOLF: {
    id: 225,
    name: 'InsanityCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.02000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  X13: {
    id: 226,
    name: 'X13Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XAI: {
    id: 227,
    name: 'Sapience AIFX',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XAP: {
    id: 228,
    name: 'API Coin',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '100.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XBC: {
    id: 229,
    name: 'BitcoinPlus',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00010000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XC: {
    id: 230,
    name: 'XCurrency',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XCH: {
    id: 231,
    name: 'ClearingHouse',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XCN: {
    id: 232,
    name: 'Cryptonite',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.02000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XCP: {
    id: 233,
    name: 'Counterparty',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '16.00000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XCR: {
    id: 234,
    name: 'Crypti',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00017818',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XDN: {
    id: 235,
    name: 'DigitalNote',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '1.00000000',
    minConf: 10000,
    depositAddress:
      'ddddecTXF5B9PDwqZXP4Bs1FwttZbhF2YTRstruKctMoFJTE3VgD5uKd4RzmTHdzkv52wWWK2NYmfJeaiTuut2Pe2RVimGCvZ',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XDP: {
    id: 236,
    name: 'Dogeparty',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XEM: {
    id: 256,
    name: 'NEM',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '15.00000000',
    minConf: 18,
    depositAddress: 'NBZMQO7ZPBYNBDUR7F75MAKA2S3DHDCIFG775N3D',
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  XHC: {
    id: 237,
    name: 'Honorcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XLB: {
    id: 238,
    name: 'Libertycoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XMG: {
    id: 239,
    name: 'Magi',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XMR: {
    id: 240,
    name: 'Monero',
    humanType: 'BTC Clone',
    currencyType: 'address-payment-id',
    txFee: '0.00010000',
    minConf: 8,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  XPB: {
    id: 241,
    name: 'Pebblecoin',
    humanType: 'Payment ID',
    currencyType: 'address-payment-id',
    txFee: '0.10000000',
    minConf: 10000,
    depositAddress:
      'PByFtxkMuoFRwrhXU19PBXLgHssTtcvTDSGzNf7Rvt5uKEf5PnRL4ccK4pWN4dpwvGhggGq12gH4bMqbxLyQGhkf3RLfzurMdK',
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XPM: {
    id: 242,
    name: 'Primecoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 2880,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  XRP: {
    id: 243,
    name: 'Ripple',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.15000000',
    minConf: 12,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  XSI: {
    id: 244,
    name: 'Stability Shares',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XST: {
    id: 245,
    name: 'StealthCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XSV: {
    id: 246,
    name: 'Silicon Valley Coin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XUSD: {
    id: 247,
    name: 'CoinoUSD',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '0.00000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XVC: {
    id: 253,
    name: 'Vcash',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 1000000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  XXC: {
    id: 248,
    name: 'CREDS',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  YACC: {
    id: 249,
    name: 'YACCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  YANG: {
    id: 250,
    name: 'Yangcoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  YC: {
    id: 251,
    name: 'YellowCoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  YIN: {
    id: 252,
    name: 'Yincoin',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.01000000',
    minConf: 10000,
    depositAddress: null,
    disabled: 1,
    delisted: 1,
    frozen: 0,
    isGeofenced: 0,
  },
  ZEC: {
    id: 286,
    name: 'Zcash',
    humanType: 'BTC Clone',
    currencyType: 'address',
    txFee: '0.00100000',
    minConf: 8,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
  ZRX: {
    id: 293,
    name: '0x',
    humanType: 'Sweep to Main Account',
    currencyType: 'address',
    txFee: '5.00000000',
    minConf: 30,
    depositAddress: null,
    disabled: 0,
    delisted: 0,
    frozen: 0,
    isGeofenced: 0,
  },
};
